### ISSUE TITLE
I'm not seeing any mention of scopes required

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-debug-java#2]
I've been testing a GCE setup and it took me a while to figure out that the instances had to have the https://www.googleapis.com/auth/cloud_debugger scope to work.  

I would expect that to be mentioned in this repo and on https://cloud.google.com/debugger/docs/setting-up-on-compute-engine

**Comment by mctavish** [comment]
Things have changed a *lot* since this issue was cut.  Given that the Cloud Debugger service has been shut down and the Firebase backend should be used at this point, I'll leave a link to the current working sample which calls out required scopes: https://github.com/GoogleCloudPlatform/snapshot-debugger/tree/main/samples/java/gce
