### ISSUE TITLE
GKE - Debugger crashes on boot

### ISSUE THREAD

**Issue by MaikJaek** [GoogleCloudPlatform/cloud-debug-java#8]
Hi there,

I'm trying to run the java cloud debugger inside GKE. 
Unfortunately, once the VM starts, the cloud debugger crashes with: 

I0724 13:56:49.782296    36 jni_logger.cc:31] Initializing ClassPathLookup, default classpath: true, extra classpath: []
I0724 13:56:49.881603    36 jni_logger.cc:31] Total size of indexed resources database: 3092 bytes
I0724 13:56:49.902678    36 jvm_internals.cc:131] ClassPathLookup constructor time: 159468 microseconds
I0724 13:56:49.903113    36 yaml_data_visibility_config_reader.cc:37] debugger-blacklist.yaml was not found.  Using default settings.
E0724 13:56:49.920346    36 jni_utils.h:372] GcpHubClient.<init>: java.lang.RuntimeException: Failed to initialize service account authentication
	at com.google.devtools.cdbg.debuglets.java.GcpEnvironment.getMetadataQuery(Unknown Source)
	at com.google.devtools.cdbg.debuglets.java.GcpHubClient.<init>(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.google.devtools.cdbg.debuglets.java.ServiceAccountAuth
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.google.devtools.cdbg.debuglets.java.InternalsClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	... 2 more
E0724 13:56:49.925649    36 jni_bridge.cc:50] Failed to instantiate HubClient Java class
E0724 13:56:49.925870    36 worker.cc:145] HubClient not available: debugger thread can't continue.
I0724 13:56:49.925930    36 jvmti_agent_thread.cc:103] Agent thread exited: CloudDebugger_main_worker_thread

Any ideas how to get this running?

**Comment by MaikJaek** [comment]
Further information to understand the problem's cause: 

**The base docker image used is: FROM gcr.io/google-appengine/openjdk**

**The start command of the java process is:**
Start command: java -showversion -agentpath:/opt/cdbg/cdbg_java_agent.so=--log_dir=/var/log/app_engine,--alsologtostderr=true -agentpath:/opt/cprof/profiler_java_agent.so=--logtostderr,--cprof_service=persistent-cart-services -Xms240M -Xmx240M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:+PrintCommandLineFlags -Dcom.google.cdbg.module=myapp -Dcom.google.cdbg.version=poc-23 -jar app.jar
-XX:InitialHeapSize=251658240 -XX:MaxHeapSize=251658240 -XX:+ParallelRefProcEnabled -XX:+PrintCommandLineFlags -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseG1GC

**Comment by xinghuadou-google** [comment]
Sorry for the late response.

Did you download (1) cdbg_java_agent_gce.tar.gz or (2) cdbg_java_agent**_service_account**.tar.gz?
By any change is GOOGLE_APPLICATION_CREDENTIALS set, even if it's to the empty string?
If you are using (1), can you try using (2) instead?

**Comment by wuservices** [comment]
@xinghuadou-google I think I ran into the same problem and for me at least, you're on the right track.

@MaikJaek mentioned he was using the Google OpenJDK base image. So am I. As you anticipated, the base image is using the [version of the agent without service account support](https://github.com/GoogleCloudPlatform/openjdk-runtime/blob/e1706d48605279e163cbcd50f541d10cc6211cf7/openjdk8/src/main/docker/Dockerfile#L41/).

I'm also using `GOOGLE_APPLICATION_CREDENTIALS` because I have a third-party library, which needs the service account JSON.

@xinghuadou-google would Google be able to update the default OpenJDK image to allow service accounts, especially since it's the best practice for multi-service apps to make permissions as granular as possible?
